version: '3'
services:
  #php service
  app-blue:
    build:
      context: .
      dockerfile: ./infrastructure/docker/php-fpm/Dockerfile
    image: banisedki/php-fpm
    container_name: php-fpm-blue
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - app-network
      - blue-network
  #mysql
  mysql-blue:
    image: mcr.microsoft.com/mssql/server
    container_name: mysql-blue
    restart: unless-stopped
    command: mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD:
    ports:
      - 3308:3306
    volumes:
      - ./:/var/www/html
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    networks:
      - app-network
      - blue-network
  #Nginx server
  webserver-blue:
    build:
      context: .
      dockerfile: ./infrastructure/docker/nginx/Dockerfile
    image: banisedki/nxtya_nginx
    container_name: webserver-blue
    restart: unless-stopped
    tty: true
    ports:
      - "82:80"
      - "444:443"
    volumes:
      - ./:/var/www/html
    networks:
      - app-network
      - blue-network
  # Redis service
  redis-blue:
    image: redis:latest
    container_name: redis-blue
    restart: unless-stopped
    networks:
      - app-network
      - blue-network
# Docker Networks
networks:
  app-network:
    driver: bridge
  blue-network:
    driver: bridge
# Volumes
volumes:
  dbdata:
    driver: local
